[2021-06-04 16:16:49]	[py]	[exception]	[2021-06-04 16:16:48:	SQLSTATE[42S22]: Column not found: 1054 Unknown column 'language' in 'field list', query was: INSERT INTO `user` (`openid`, `nickname`, `sex`, `language`, `city`, `province`, `country`, `headimgurl`, `privilege`, `unionid`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)	D:\webservice\php\PEAR\Zend\Db\Statement\Pdo.php on line 235	#0 D:\webservice\php\PEAR\Zend\Db\Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 D:\webservice\php\PEAR\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 D:\webservice\php\PEAR\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `us...', Array)
#3 D:\webservice\php\PEAR\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `us...', Array)
#4 D:\webservice\web\react\php\application\models\Base.php(58): Zend_Db_Adapter_Abstract->insert('user', Array)
#5 D:\webservice\web\react\php\application\controllers\IndexController.php(103): Base->insert('user', Array)
#6 D:\webservice\php\PEAR\Zend\Controller\Action.php(503): IndexController->wechatloginAction()
#7 D:\webservice\php\PEAR\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('wechatloginActi...')
#8 D:\webservice\php\PEAR\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 D:\webservice\web\react\php\htdocs\index.php(58): Zend_Controller_Front->dispatch()
#10 {main}	]EOR
[2021-06-04 16:17:45]	[py]	[exception]	[2021-06-04 16:17:45:	SQLSTATE[42S22]: Column not found: 1054 Unknown column 'language' in 'field list', query was: INSERT INTO `user` (`openid`, `nickname`, `sex`, `language`, `city`, `province`, `country`, `headimgurl`, `privilege`, `unionid`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)	D:\webservice\php\PEAR\Zend\Db\Statement\Pdo.php on line 235	#0 D:\webservice\php\PEAR\Zend\Db\Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 D:\webservice\php\PEAR\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 D:\webservice\php\PEAR\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `us...', Array)
#3 D:\webservice\php\PEAR\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `us...', Array)
#4 D:\webservice\web\react\php\application\models\Base.php(58): Zend_Db_Adapter_Abstract->insert('user', Array)
#5 D:\webservice\web\react\php\application\controllers\IndexController.php(104): Base->insert('user', Array)
#6 D:\webservice\php\PEAR\Zend\Controller\Action.php(503): IndexController->wechatloginAction()
#7 D:\webservice\php\PEAR\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('wechatloginActi...')
#8 D:\webservice\php\PEAR\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 D:\webservice\web\react\php\htdocs\index.php(58): Zend_Controller_Front->dispatch()
#10 {main}	]EOR
[2021-06-04 16:18:09]	[py]	[exception]	[2021-06-04 16:18:09:	SQLSTATE[42S22]: Column not found: 1054 Unknown column 'language' in 'field list', query was: INSERT INTO `user` (`openid`, `nickname`, `sex`, `language`, `city`, `province`, `country`, `headimgurl`, `privilege`, `unionid`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)	D:\webservice\php\PEAR\Zend\Db\Statement\Pdo.php on line 235	#0 D:\webservice\php\PEAR\Zend\Db\Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 D:\webservice\php\PEAR\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 D:\webservice\php\PEAR\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `us...', Array)
#3 D:\webservice\php\PEAR\Zend\Db\Adapter\Abstract.php(576): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `us...', Array)
#4 D:\webservice\web\react\php\application\models\Base.php(58): Zend_Db_Adapter_Abstract->insert('user', Array)
#5 D:\webservice\web\react\php\application\controllers\IndexController.php(104): Base->insert('user', Array)
#6 D:\webservice\php\PEAR\Zend\Controller\Action.php(503): IndexController->wechatloginAction()
#7 D:\webservice\php\PEAR\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('wechatloginActi...')
#8 D:\webservice\php\PEAR\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 D:\webservice\web\react\php\htdocs\index.php(58): Zend_Controller_Front->dispatch()
#10 {main}	]EOR
[2021-06-04 17:15:21]	[py]	[exception]	[2021-06-04 17:15:21:	SQLSTATE[HY093]: Invalid parameter number: no parameters were bound, query was: SELECT COUNT(*) FROM `user` WHERE (openid = ?)	D:\webservice\php\PEAR\Zend\Db\Statement\Pdo.php on line 235	#0 D:\webservice\php\PEAR\Zend\Db\Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 D:\webservice\php\PEAR\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 D:\webservice\php\PEAR\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#3 D:\webservice\php\PEAR\Zend\Db\Adapter\Abstract.php(828): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 D:\webservice\web\react\php\application\models\Base.php(50): Zend_Db_Adapter_Abstract->fetchOne(Object(Zend_Db_Select))
#5 D:\webservice\web\react\php\application\controllers\IndexController.php(86): Base->select('fetchOne', 'user', Array)
#6 D:\webservice\php\PEAR\Zend\Controller\Action.php(503): IndexController->wechatloginAction()
#7 D:\webservice\php\PEAR\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('wechatloginActi...')
#8 D:\webservice\php\PEAR\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 D:\webservice\web\react\php\htdocs\index.php(58): Zend_Controller_Front->dispatch()
#10 {main}	]EOR
[2021-06-04 18:17:37]	[py]	[exception]	[2021-06-04 18:17:37:	SQLSTATE[HY093]: Invalid parameter number: no parameters were bound, query was: SELECT COUNT(*) FROM `apply` WHERE (userid = ?) AND (state = '2')	D:\webservice\php\PEAR\Zend\Db\Statement\Pdo.php on line 235	#0 D:\webservice\php\PEAR\Zend\Db\Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 D:\webservice\php\PEAR\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 D:\webservice\php\PEAR\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#3 D:\webservice\php\PEAR\Zend\Db\Adapter\Abstract.php(828): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 D:\webservice\web\react\php\application\models\Base.php(50): Zend_Db_Adapter_Abstract->fetchOne(Object(Zend_Db_Select))
#5 D:\webservice\web\react\php\application\controllers\IndexController.php(132): Base->select('fetchOne', 'apply', Array)
#6 D:\webservice\php\PEAR\Zend\Controller\Action.php(503): IndexController->wechatloginAction()
#7 D:\webservice\php\PEAR\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('wechatloginActi...')
#8 D:\webservice\php\PEAR\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 D:\webservice\web\react\php\htdocs\index.php(58): Zend_Controller_Front->dispatch()
#10 {main}	]EOR
[2021-06-04 18:19:07]	[py]	[exception]	[2021-06-04 18:19:07:	SQLSTATE[HY093]: Invalid parameter number: no parameters were bound, query was: SELECT COUNT(*) FROM `apply` WHERE (userid = ?) AND (state = '2')	D:\webservice\php\PEAR\Zend\Db\Statement\Pdo.php on line 235	#0 D:\webservice\php\PEAR\Zend\Db\Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 D:\webservice\php\PEAR\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 D:\webservice\php\PEAR\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#3 D:\webservice\php\PEAR\Zend\Db\Adapter\Abstract.php(828): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 D:\webservice\web\react\php\application\models\Base.php(50): Zend_Db_Adapter_Abstract->fetchOne(Object(Zend_Db_Select))
#5 D:\webservice\web\react\php\application\controllers\IndexController.php(133): Base->select('fetchOne', 'apply', Array)
#6 D:\webservice\php\PEAR\Zend\Controller\Action.php(503): IndexController->wechatloginAction()
#7 D:\webservice\php\PEAR\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('wechatloginActi...')
#8 D:\webservice\php\PEAR\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 D:\webservice\web\react\php\htdocs\index.php(58): Zend_Controller_Front->dispatch()
#10 {main}	]EOR
[2021-06-04 18:19:20]	[py]	[exception]	[2021-06-04 18:19:20:	SQLSTATE[HY093]: Invalid parameter number: no parameters were bound, query was: SELECT COUNT(*) FROM `apply` WHERE (userid = ?) AND (state = '2')	D:\webservice\php\PEAR\Zend\Db\Statement\Pdo.php on line 235	#0 D:\webservice\php\PEAR\Zend\Db\Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 D:\webservice\php\PEAR\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 D:\webservice\php\PEAR\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#3 D:\webservice\php\PEAR\Zend\Db\Adapter\Abstract.php(828): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 D:\webservice\web\react\php\application\models\Base.php(50): Zend_Db_Adapter_Abstract->fetchOne(Object(Zend_Db_Select))
#5 D:\webservice\web\react\php\application\controllers\IndexController.php(134): Base->select('fetchOne', 'apply', Array)
#6 D:\webservice\php\PEAR\Zend\Controller\Action.php(503): IndexController->wechatloginAction()
#7 D:\webservice\php\PEAR\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('wechatloginActi...')
#8 D:\webservice\php\PEAR\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 D:\webservice\web\react\php\htdocs\index.php(58): Zend_Controller_Front->dispatch()
#10 {main}	]EOR
[2021-06-04 18:20:23]	[py]	[exception]	[2021-06-04 18:20:23:	SQLSTATE[HY093]: Invalid parameter number: no parameters were bound, query was: SELECT COUNT(*) FROM `apply` WHERE (userid = ?) AND (state = '2')	D:\webservice\php\PEAR\Zend\Db\Statement\Pdo.php on line 235	#0 D:\webservice\php\PEAR\Zend\Db\Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 D:\webservice\php\PEAR\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 D:\webservice\php\PEAR\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#3 D:\webservice\php\PEAR\Zend\Db\Adapter\Abstract.php(828): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 D:\webservice\web\react\php\application\models\Base.php(50): Zend_Db_Adapter_Abstract->fetchOne(Object(Zend_Db_Select))
#5 D:\webservice\web\react\php\application\controllers\IndexController.php(135): Base->select('fetchOne', 'apply', Array)
#6 D:\webservice\php\PEAR\Zend\Controller\Action.php(503): IndexController->wechatloginAction()
#7 D:\webservice\php\PEAR\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('wechatloginActi...')
#8 D:\webservice\php\PEAR\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 D:\webservice\web\react\php\htdocs\index.php(58): Zend_Controller_Front->dispatch()
#10 {main}	]EOR
